---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-appstudio-qe/e2e-base?rev={{ revision }}
    build.appstudio.redhat.com/commit_sha: '{{ revision }}'
    build.appstudio.redhat.com/pull_request_number: '{{ pull_request_number }}'
    build.appstudio.redhat.com/target_branch: '{{ target_branch }}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch == "push-rpms-to-pulp-base"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: pulp-rpm-app
    appstudio.openshift.io/component: testcomp
    pipelines.appstudio.openshift.io/type: build
  name: testcomp-on-pull-request
  namespace: jinqi-tenant
spec:
  params:
    - name: ociStorage
      value: >-
        quay.io/redhat-user-workloads/jinqi-tenant/testcomp:pr{{pull_request_number}}-{{revision}}
    - name: package-name
      value: hello
    - name: git-url
      value: "{{ source_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: target-branch
      value: "{{ target_branch }}"
    - name: build-architectures
      value: ["x86_64"]
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: "https://github.com/konflux-ci/rpmbuild-pipeline.git"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipeline/build-rpm-package.yaml
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
